global:
  poll_interval_s: 10
  server:
    host: 0.0.0.0
    port: 5000
benches:
- name: themis
  hostname: themis-fw-hil-12
  ip: 10.80.11.101
  ssh:
    host: 10.80.11.101
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: themis-fw-hil-12
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OE6P-if00-port0
      ports:
      - CodeWarrior TAP S32Z debugger
      - USB hub 4; wdt_relays[1](A4002Cse), SENT gateway[3]
      - USB hub 3; pemicro[1], s32k serial[2](BK00TWYF), SMU serial[3](FTD3TO1K),
        RTU serial[4](BK00TWYA)
      - USB power control for the Radmoon2 ethernet PHY adapter
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0033ESY-if00-port0
      ports:
      - USB port that the WDT relay device is connected to
      - USB hub with all 4 PCAN adapters
      - LabJack T7
      - port_unused_3
    relay_boards:
    - name: dut_relays
      identifier: A4002Cp8
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdt_relays
      identifier: A907TD5M
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    labjack_devices:
    - name: labjack
      powered_by:
        hub_index: 1
        port: 2
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enp0s20f0u1u1u1c2
      device_ip: 192.168.1.15
    - name: dut_ethernet
      interface: enp3s0
- name: helen
  hostname: helen-fw-hil-20
  ip: 10.80.11.108
  ssh:
    host: 10.80.11.108
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: helen-fw-hil-20
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P1ZW-if00-port0
      ports:
      - USB port that the S32 Debugger (ZAP) is connected to
      - Chained Anker 4-port hub with relay devices connected
      - Chained Anker 4-port hub with S32k PeMicro debugger, S32K serial, SMU serial,
        RTU serial
      - usb_hub_0_port_unused_3
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OZBX-if00-port0
      ports:
      - USB port that PCAN1 is connected to
      - USB port that PCAN0 is connected to
      - USB port that PCAN2 is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    relay_boards:
    - name: dut_relays_0
      identifier: A907TD4J
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: dut_relays_1
      identifier: AH05I3J0
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enx00e04cb20828
      device_ip: 192.168.1.15
    - name: dut_ethernet
      interface: enp3s0
- name: elpaso
  hostname: elpaso-hw-bench-5
  ip: 10.80.11.28
  ssh:
    host: 10.80.11.28
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: elpaso-hw-bench-5
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_2
      serial_path: /dev/serial/by-id/usb-StarTech.com_5G4AINDRM-USB-A-HUB_B0B7K2U4-if00-port0
      ports:
      - Sainsmart relay board for DUT power and boot mode control (AH05I4ZX)
      - USB hub 5; PCAN0[1]34045; PCAN1[2]34235; PCAN2[3]34052; PCAN3[4]39911
      - LabJack T7
      - Unused
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P1EX-if00-port0
      ports:
      - CodeWarrior TAP S32Z debugger
      - USB hub 4; wdt_relays[1](AH05I53H), SENT gateway[3]
      - USB hub 3; pemicro[1], s32k serial[2](AU0K41SH), SMU serial[3](AB0L6LBL),
        RTU serial[4](AU0K3DGT)
      - Unused
    relay_boards:
    - name: dut_relays_0
      identifier: AH05I4ZX
      powered_by:
        hub_index: 0
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdt_relays
      identifier: AH05I53H
      powered_by:
        hub_index: 1
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: false
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    labjack_devices:
    - name: labjack
      powered_by:
        hub_index: 0
        port: 2
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enp0s20f0u1u1c2
      device_ip: 192.168.1.15
    - name: dut_ethernet
      interface: enp3s0
- name: jericho
  hostname: jericho-fw-hil-31
  ip: 10.80.10.98
  ssh:
    host: 10.80.10.98
    user: dev
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: jericho-fw-hil-31
    queue: fw_hil
  devices:
    usb_hubs: []
    relay_boards: []
- name: mater
  hostname: mater-fw-hil-19
  ip: 10.80.10.18
  ssh:
    host: 10.80.10.18
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: mater-fw-hil-19
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P3XS-if00-port0
      ports:
      - USB port that the S32 Debugger (ZAP) is connected to
      - USB port that DUT relay device is connected to
      - Chained Anker 4-port hub with S32k PeMicro debugger, S32K serial, SMU serial,
        RTU serial
      - port_unused_3
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OE31-if00-port0
      ports:
      - USB port that PCAN1 is connected to
      - USB port that PCAN0 is connected to
      - USB port that PCAN2 is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    relay_boards:
    - name: dut_relays
      identifier: AH05I4ZH
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdg_relays
      identifier: AH05I50P
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    ethernet_devices:
    - name: dut_ethernet
      interface: enp87s0
- name: mikey
  hostname: mikey-fw-hil-29
  ip: 10.80.11.15
  ssh:
    host: 10.80.11.15
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: mikey-fw-hil-29
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-StarTech.com_5G4AINDRM-USB-A-HUB_B0BCBP9C-if00-port0
      ports:
      - Chained Anker 4-port hub with S32k PeMicro debugger, S32K serial, RTU serial,
        watchdog relay board
      - Chained Anker 4-port hub with S32 Debugger (ZAP), DUT relay board, SMU serial
      - port_unused_2
      - port_unused_3
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-StarTech.com_5G4AINDRM-USB-A-HUB_B0B7KE70-if00-port0
      ports:
      - USB port that PCAN (37233) is connected to
      - USB port that PCAN (36924) is connected to
      - USB port that PCAN2 (37547) is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    relay_boards:
    - name: dut_relays
      identifier: AQ02HF9H
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: true
      - label: boot_mod_2
        inverted: false
        default: true
    - name: wdg_relays
      identifier: A4002Cpl
      powered_by:
        hub_index: 0
        port: 0
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    ethernet_devices:
    - name: dut_ethernet
      interface: enp3s0
- name: cassiopeia
  hostname: cassiopeia-fw-hil-17
  ip: 10.80.11.103
  ssh:
    host: 10.80.11.103
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: cassiopeia-fw-hil-17
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_pcan
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P3WN-if00-port0
      ports:
      - USB port that PCAN0 (37528) is connected to
      - USB port that PCAN1 (36931) is connected to
      - USB port that PCAN2 (36940) is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    - name: usb_hub_misc
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OYQC-if00-port0
      ports:
      - USB port that DUT relay device is connected to
      - USB port that the S32 Debugger (ZAP) is connected to
      - Chained Anker 4-port hub with S32k PeMicro debugger and RTU, SMU, and S32k
        UART
      - 'TODO: connect relay 2, with fs86/fs82 relays'
    relay_boards:
    - name: dut_relays
      identifier: AH05I4P7
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdt_relays
      identifier: AH05I56F
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: false
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    ethernet_devices:
    - name: dut_ethernet
      interface: enp3s0
- name: lemonade
  hostname: lemonade-fw-hil-28
  ip: 10.80.10.24
  ssh:
    host: 10.80.10.24
    user: dev
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: lemonade-fw-hil-28
    queue: fw_hil
  devices:
    usb_hubs: []
    relay_boards: []
    ethernet_devices:
    - name: dut_eth
      interface: enp3s0
- name: mnemosyne
  hostname: mnemosyne-fw-hil-6
  ip: 10.80.10.57
  ssh:
    host: 10.80.10.57
    user: dev
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: mnemosyne-fw-hil-6
    queue: fw_hil
  devices:
    usb_hubs: []
    relay_boards: []
