global:
  poll_interval_s: 10
  server:
    host: 0.0.0.0
    port: 5000
benches:
- name: themis
  hostname: themis-fw-hil-12
  ip: 10.80.11.101
  ssh:
    host: 10.80.11.101
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: themis-fw-hil-12
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OE6P-if00-port0
      ports:
      - CodeWarrior TAP S32Z debugger
      - USB hub 4; wdt_relays[1](A4002Cse), SENT gateway[3]
      - USB hub 3; pemicro[1], s32k serial[2](BK00TWYF), SMU serial[3](FTD3TO1K),
        RTU serial[4](BK00TWYA)
      - USB power control for the Radmoon2 ethernet PHY adapter
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0033ESY-if00-port0
      ports:
      - USB port that the WDT relay device is connected to
      - USB hub with all 4 PCAN adapters
      - LabJack T7
      - port_unused_3
    relay_boards:
    - name: dut_relays
      identifier: A4002Cp8
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdt_relays
      identifier: A907TD5M
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    serial_devices:
    - name: mcu_s32k_debug_serial
      identifier: BK00TWYF
    - name: rtu_s32z_debug_serial
      identifier: BK00TWYA
    - name: smu_s32z_debug_serial
      identifier: FTD3TO1K
    labjack_devices:
    - name: labjack
      powered_by:
        hub_index: 1
        port: 2
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enp0s20f0u1u1u1c2
      device_ip: 192.168.1.15
- name: helen
  hostname: helen-fw-hil-20
  ip: 10.80.8.251
  ssh:
    host: 10.80.8.251
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: helen-fw-hil-20
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P1ZW-if00-port0
      ports:
      - USB port that the S32 Debugger (ZAP) is connected to
      - Chained Anker 4-port hub with relay devices connected
      - Chained Anker 4-port hub with S32k PeMicro debugger, S32K serial, SMU serial,
        RTU serial
      - usb_hub_0_port_unused_3
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OYSO-if00-port0
      ports:
      - USB port that PCAN1 is connected to
      - USB port that PCAN0 is connected to
      - USB port that PCAN2 is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    relay_boards:
    - name: dut_relays_0
      identifier: A907TD4J
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: dut_relays_1
      identifier: AH05I3J0
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    serial_devices:
    - name: mcu_s32k_debug_serial
      identifier: AU0K3HGK
    - name: rtu_s32z_debug_serial
      identifier: AU0K3GYB
    - name: smu_s32z_debug_serial
      identifier: FT98RHHT
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enx00e04cb20828
      device_ip: 192.168.1.15
- name: elpaso
  hostname: elpaso-hw-bench-5
  ip: 10.80.11.28
  ssh:
    host: 10.80.11.28
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: elpaso-hw-bench-5
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_2
      serial_path: /dev/serial/by-id/usb-StarTech.com_5G4AINDRM-USB-A-HUB_B0B7K2U4-if00-port0
      ports:
      - Sainsmart relay board for DUT power and boot mode control (AH05I4ZX)
      - USB hub 5; PCAN0[1]34045; PCAN1[2]34235; PCAN2[3]34052; PCAN3[4]39911
      - LabJack T7
      - Unused
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P1EX-if00-port0
      ports:
      - CodeWarrior TAP S32Z debugger
      - USB hub 4; wdt_relays[1](AH05I53H), SENT gateway[3]
      - USB hub 3; pemicro[1], s32k serial[2](AU0K41SH), SMU serial[3](AB0L6LBL),
        RTU serial[4](AU0K3DGT)
      - Unused
    relay_boards:
    - name: dut_relays_0
      identifier: AH05I4ZX
      powered_by:
        hub_index: 0
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdt_relays
      identifier: AH05I53H
      powered_by:
        hub_index: 1
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: false
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    serial_devices:
    - name: mcu_s32k_debug_serial
      identifier: AU0K41SH
    - name: rtu_s32z_debug_serial
      identifier: AU0K3DGT
    - name: smu_s32z_debug_serial
      identifier: AB0L6LBL
    labjack_devices:
    - name: labjack
      powered_by:
        hub_index: 0
        port: 2
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enp0s20f0u1u1c2
      device_ip: 192.168.1.15
- name: coconut
  hostname: coconut-fw-hil-18
  ip: 10.80.10.25
  ssh:
    host: 10.80.10.25
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: coconut-fw-hil-18
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_pcan
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B0036AWH-if00-port0
      ports:
      - USB port that PCAN1 is connected to
      - USB port that PCAN2 is connected to
      - USB port that PCAN0 is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    - name: usb_hub_misc
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B00337ZD-if00-port0
      ports:
      - USB port that DUT relay device is connected to
      - USB port that the S32 Debugger (ZAP) is connected to
      - Chained Anker 4-port hub with S32k PeMicro debugger and RTU, SMU, and S32k
        UART
      - port_unused_3
    relay_boards:
    - name: dut_relays
      identifier: CVVDM0ZB
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdg_relays
      identifier: AH05I4ZM
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    serial_devices:
    - name: mcu_s32k_debug_serial
      identifier: AU0K3F5A
    - name: rtu_s32z_debug_serial
      identifier: AU0K3J5F
    - name: smu_s32z_debug_serial
      identifier: FT98RVUO
    ethernet_devices:
    - name: fl3x_ethernet
      interface: enp0s20f0u4u1
      device_ip: 192.168.1.15
- name: mater
  hostname: mater-fw-hil-19
  ip: 10.80.10.18
  ssh:
    host: 10.80.10.18
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: mater-fw-hil-19
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_0
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P3XS-if00-port0
      ports:
      - USB port that the S32 Debugger (ZAP) is connected to
      - USB port that DUT relay device is connected to
      - Chained Anker 4-port hub with S32k PeMicro debugger, S32K serial, SMU serial,
        RTU serial
      - port_unused_3
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OE31-if00-port0
      ports:
      - USB port that PCAN1 is connected to
      - USB port that PCAN0 is connected to
      - USB port that PCAN2 is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    relay_boards:
    - name: dut_relays
      identifier: AH05I4ZH
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdg_relays
      identifier: AH05I50P
      powered_by:
        hub_index: 0
        port: 1
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: true
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    serial_devices:
    - name: mcu_s32k_debug_serial
      identifier: AU0K40VB
    - name: rtu_s32z_debug_serial
      identifier: AU0K3FHR
    - name: smu_s32z_debug_serial
      identifier: FTEIO7H5
- name: cassiopeia
  hostname: cassiopeia-fw-hil-17
  ip: 10.80.11.103
  ssh:
    host: 10.80.11.103
    user: dev
    sudo_user: bk
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: cassiopeia-fw-hil-17
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_pcan
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P3WN-if00-port0
      ports:
      - USB port that PCAN0 (37528) is connected to
      - USB port that PCAN1 (36931) is connected to
      - USB port that PCAN2 (36940) is connected to
      - USB power control for the Radmoon2 ethernet PHY adapter
    - name: usb_hub_misc
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001OYQC-if00-port0
      ports:
      - USB port that DUT relay device is connected to
      - USB port that the S32 Debugger (ZAP) is connected to
      - Chained Anker 4-port hub with S32k PeMicro debugger and RTU, SMU, and S32k
        UART
      - 'TODO: connect relay 2, with fs86/fs82 relays'
    relay_boards:
    - name: dut_relays
      identifier: AH05I4P7
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: main_12v
        inverted: true
        default: false
      - label: wdg_dbg_fs26
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: false
        default: false
      - label: boot_mod_2
        inverted: false
        default: false
    - name: wdt_relays
      identifier: AH05I56F
      powered_by:
        hub_index: 1
        port: 0
      channels:
      - label: wdg_dbg_fs86
        inverted: true
        default: true
      - label: wdg_dbg_pf50
        inverted: false
        default: true
      - label: unused_ch2
        inverted: false
        default: false
      - label: unused_ch3
        inverted: false
        default: false
    serial_devices:
    - name: mcu_s32k_debug_serial
      identifier: AU0K3GJ6
    - name: rtu_s32z_debug_serial
      identifier: AU0K3GDJ
    - name: smu_s32z_debug_serial
      identifier: FTEIO7J0
- name: lemonade
  hostname: lemonade-fw-hil-28
  ip: 10.80.10.24
  ssh:
    host: 10.80.10.24
    user: dev
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: lemonade-fw-hil-28
    queue: fw_hil
  devices:
    usb_hubs: []
    relay_boards: []
- name: mnemosyne
  hostname: mnemosyne-fw-hil-6
  ip: 10.80.10.57
  ssh:
    host: 10.80.10.57
    user: dev
  buildkite:
    service: buildkite-agent-bk.service
    agent_name: mnemosyne-fw-hil-6
    queue: fw_hil
  devices:
    usb_hubs:
    - name: usb_hub_1
      serial_path: /dev/serial/by-id/usb-StarTech.com_5G7AINDRM-USB-A-HUB_BGAUDYAG-if00-port0
      ports:
      - High pine FT4232 quad-serial and gpio device. For debug serial and BMODE gpio
        control.
      - SMU serial port; TODO remove after rework and use ft4232 instead
      - Mach systems SENT1 device
      - Mach systems SENT2 device
    - name: usb_hub_2
      serial_path: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_B001P3VS-if00-port0
      ports:
      - Unused
      - Unused
      - Unused
      - 'USB31000S USB-to-Ethernet #2'
    relay_boards: []
    denkovi_relays:
    - name: dut_relays
      host: 192.168.1.100
      channels:
      - label: main_12v
        inverted: false
        default: true
      - label: fs86_dbg_vbos
        inverted: false
        default: true
      - label: pf50_dbg_vbos
        inverted: false
        default: true
      - label: usb_hub_1_pwr
        inverted: true
        default: true
      - label: usb_hub_2_pwr
        inverted: true
        default: true
      - label: lin_12v_pwr
        inverted: false
        default: true
      - label: unused_ch6
        inverted: true
        default: true
      - label: media_conv_1_pwr
        inverted: true
        default: true
      - label: media_conv_2_pwr
        inverted: true
        default: true
      - label: psi5_pwr
        inverted: true
        default: true
      - label: boot_mod_1
        inverted: true
        default: true
      - label: boot_mod_2
        inverted: true
        default: true
      - label: unused_ch12
        inverted: false
        default: false
      - label: unused_ch13
        inverted: false
        default: false
      - label: unused_ch14
        inverted: false
        default: false
      - label: unused_ch15
        inverted: false
        default: false
    serial_devices:
    - name: smu_s32z_debug_serial
      identifier: FT98RH82
    - name: rtu_s32z_debug_serial
      identifier: /dev/serial/by-id/usb-FTDI_Quad_RS232-HS-if01-port0
    labjack_devices:
    - name: labjack
      powered_by:
        hub_index: 0
        port: 5
    ethernet_devices:
    - name: LAN2
      interface: enp3s0
    - name: usb_eth_1
      interface: enx00249b8cb565
    - name: usb_eth_2
      interface: enx00249b8cb550
    intrepid_devices:
    - name: s32z_can1_conn_j10
      serial_number: FF0552
      channel_names:
      - s32z_can1_conn_j10
      - s32z_can2_conn_j10
      - s32z_can3_conn_j15
      - s32z_can4_conn_j15
      - s32z_can5_conn_j9
      - s32z_can6_conn_j9
      - s32z_can7_conn_j15
      - s32z_can8_conn_j15
      - s32z_can9_conn_j10
      - s32z_can10_conn_j10
